import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import FristNavBar from "@/components/shared/FristNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#C3D7E7]">
          <FristNavBar />
        </div>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
